name: publish

on:
  push:
    branches: [ "develop" ]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . --tag ghcr.io/dutrieum/tp-devops:staging
          docker push ghcr.io/dutrieum/tp-devops:staging